name: pyLint

on:
  push:

jobs:
  PEP8:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install autopep8 autoflake isort black yapf

      - name: Format Code
        run: |
          autopep8 -ir --aggressive --aggressive .
          autoflake -ir --remove-all-unused-imports --remove-unused-variables .
          isort .
          black --preview .
          yapf -ir --style google .

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'pyLint: auto-fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: SamXD7
          commit_user_email: 117455545+SamXD7@users.noreply.github.com
          commit_author: SamXD7 <117455545+SamXD7@users.noreply.github.com>
